apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wh6mfyj13-nodejs 
  janus-idp.io/tekton: wh6mfyj13-nodejs
  backstage.io/kubernetes-id: wh6mfyj13-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wh6mfyj13-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  